apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: streamingapp
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: streamingapp-frontend:minikube
          imagePullPolicy: Never
          ports:
            - containerPort: 80