apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: streamingapp
spec:
  serviceName: mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6
        ports:
        - containerPort: 27017
          name: mongo
        readinessProbe:               # ← ADD here
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5      # wait 5s before first check
          periodSeconds: 10           # check every 10s  
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:                        # ← ADD this block here
      - name: mongo-storage           # must match volumeMounts name above
        persistentVolumeClaim:
          claimName: mongo-pvc        # must match metadata.name in pvc.yaml 